-- MySQL Script generated by MySQL Workbench
-- Mon Aug 30 03:27:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema obadil_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `obadil_db` ;

-- -----------------------------------------------------
-- Schema obadil_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `obadil_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `obadil_db` ;

-- -----------------------------------------------------
-- Table `obadil_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `obadil_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`users` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `total_points` INT NOT NULL DEFAULT 0,
  `last_login` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `obadil_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `obadil_db`.`users` (`username` ASC);

CREATE INDEX `fk_user_role_idx` ON `obadil_db`.`users` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`profiles` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`profiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  `phone_number` VARCHAR(10) NULL,
  `email` VARCHAR(100) NULL,
  `picture` VARCHAR(255) NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `obadil_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profile_user1_idx` ON `obadil_db`.`profiles` (`user_id` ASC);

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `obadil_db`.`profiles` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`document_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`document_types` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`document_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `type_UNIQUE` ON `obadil_db`.`document_types` (`type` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`documents` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`documents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `file_url` VARCHAR(255) NOT NULL,
  `like_count` INT NOT NULL DEFAULT 0,
  `view_count` INT NOT NULL DEFAULT 0,
  `is_solution` TINYINT NOT NULL DEFAULT 0,
  `is_video` TINYINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `document_type_id` INT UNSIGNED NOT NULL,
  `module_name` VARCHAR(100) NOT NULL,
  `university_name` VARCHAR(100) NOT NULL,
  `academic_year` YEAR NOT NULL,
  `academic_level` VARCHAR(100) NOT NULL,
  `faculty_name` VARCHAR(100) NOT NULL,
  `speciality_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_doc_type`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `obadil_db`.`document_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Document_document_type1_idx` ON `obadil_db`.`documents` (`document_type_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`faculties` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`faculties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `obadil_db`.`faculties` (`id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`departements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`departements` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`departements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `faculty_id` INT UNSIGNED NOT NULL,
  `cover_image` VARCHAR(255) NULL,
  `about` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_departement_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `obadil_db`.`faculties` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `obadil_db`.`departements` (`id` ASC);

CREATE INDEX `fk_departement_faculty1_idx` ON `obadil_db`.`departements` (`faculty_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`academic_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`academic_level` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`academic_level` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `obadil_db`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`courses` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `departement_id` INT UNSIGNED NOT NULL,
  `academic_level_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `cover_image` VARCHAR(255) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_courses_departement1`
    FOREIGN KEY (`departement_id`)
    REFERENCES `obadil_db`.`departements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_academic_level1`
    FOREIGN KEY (`academic_level_id`)
    REFERENCES `obadil_db`.`academic_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `obadil_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_courses_departement1_idx` ON `obadil_db`.`courses` (`departement_id` ASC);

CREATE INDEX `fk_courses_academic_level1_idx` ON `obadil_db`.`courses` (`academic_level_id` ASC);

CREATE INDEX `fk_courses_users1_idx` ON `obadil_db`.`courses` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`chapters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`chapters` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`chapters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `course_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_chapters_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `obadil_db`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_chapters_courses1_idx` ON `obadil_db`.`chapters` (`course_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`lecture_formats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`lecture_formats` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`lecture_formats` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `format` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `obadil_db`.`lectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`lectures` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`lectures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL,
  `chapter_id` INT UNSIGNED NOT NULL,
  `lecture_format_id` INT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lectures_chapters1`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `obadil_db`.`chapters` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lectures_lecture_formats1`
    FOREIGN KEY (`lecture_format_id`)
    REFERENCES `obadil_db`.`lecture_formats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lectures_chapters1_idx` ON `obadil_db`.`lectures` (`chapter_id` ASC);

CREATE INDEX `fk_lectures_lecture_formats1_idx` ON `obadil_db`.`lectures` (`lecture_format_id` ASC);


-- -----------------------------------------------------
-- Table `obadil_db`.`lecture_attachements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obadil_db`.`lecture_attachements` ;

CREATE TABLE IF NOT EXISTS `obadil_db`.`lecture_attachements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `lecture_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lecture_attachements_lectures1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `obadil_db`.`lectures` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_lecture_attachements_lectures1_idx` ON `obadil_db`.`lecture_attachements` (`lecture_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `obadil_db`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `obadil_db`;
INSERT INTO `obadil_db`.`roles` (`id`, `name`) VALUES (DEFAULT, 'ADMIN');
INSERT INTO `obadil_db`.`roles` (`id`, `name`) VALUES (DEFAULT, 'STUDENT');
INSERT INTO `obadil_db`.`roles` (`id`, `name`) VALUES (DEFAULT, 'TEACHER');

COMMIT;

